[package]
name = "castle-clickers"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = "0.15.3"
crossterm = "0.28.1"
rand = "0.9.0"
ratatui = "0.29.0"
rust-i18n = "3.1.3"
serde = { version = "1.0.218", features = ["derive"] }
toml = "0.8.20"
