[package]
name = "castle-clickers"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
rand = "0.9.0"
serde = { version = "1.0.218", features = ["derive"] }
toml = "0.8.20"
bevy_ecs = "0.13.0"
rust-i18n = "3.1.2"
once_cell = "1.19.0"
